### ISSUE TITLE
lock

### ISSUE THREAD

**Issue by opo58** [kudelskisecurity/ecdsa-dump-bitcoin#5]
-blockparser sigdump ~/csvdump ~/.bitcoin
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-explorer-1.2.17/src/parser/block_index.rs:67:13:
assertion `left == right` failed: some block info missing from block index levelDB,delete Bitcoin folder and re-download!
  left: 858694
 right: 858693
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by coolmib** [comment]
> -blockparser sigdump ~/csvdump ~/.bitcoin thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-explorer-1.2.17/src/parser/block_index.rs:67:13: assertion `left == right` failed: some block info missing from block index levelDB,delete Bitcoin folder and re-download! left: 858694 right: 858693 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I solve it by remove the assertion checking part
